version: 2
jobs:
  build:
      docker:
        - image: circleci/classic:latest
      working_directory: /usr/src
      steps:
        - checkout                    
        - run:
            name: Build Docker Image
            command: |
            docker build -f Dockerfile.integration . -t lemon-mart:$CIRCLE_BRANCH --build-arg CACHEBUST=$(date +%s)
            mkdir -p docker-cache
            docker save -o docker-cache/built-image.tar lemon-mart:$CIRCLE_BRANCH
        