version: 2
jobs:
  build:
      docker:
        - image: circleci/classic:latest
      working_directory: /usr/src
      steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: false
        - run:
            name: Build Docker Image
            command: |
              npm run build:ci