version: 2
jobs:
  build:
    docker:
      - image: docker:17.12.0-ce-git
    working_directory: /usr/src
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Execute Pipeline (Build Source -> Test -> Build Web Server)
          # code is checked out in the pipeline, consider copying from CI to Pipeline
          # consider caching node_modules or switching to npm ci option when it becomes stable
          command: |
            docker build -f Dockerfile.integration . -t lemon-mart:$CIRCLE_BRANCH --build-arg CACHEBUST=$(date +%s)
            mkdir -p docker-cache
            docker save -o docker-cache/built-image.tar lemon-mart:$CIRCLE_BRANCH
      - save_cache:
          key: built-image-{{ .BuildNum }}
          paths:
            - docker-cache
      - store_artifacts:
          path: docker-cache/built-image.tar
          destination: built-image.tar
      - store_test_results:
          path: tests/units.html

  publish:
    docker:
      - image: docker:17.12.0-ce-git
    working_directory: /usr/src
    steps:
      - restore_cache:
        keys:
          - built-image-{{ .BuildNum }}
          - built-image
      - setup_remote_docker
      - run:
          name: Sign into AWS ecr
          command: $(aws ecr get-login --no-include-email --region us-east-1)
      - run:
          name: Push it to ECR
          command: |
            docker load < docker-cache/built-image.tar
            docker tag my_app:$CIRCLE_BRANCH $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/lemon-mart:$CIRCLE_BRANCH
            docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/lemon-mart:$CIRCLE_BRANCH
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter